name: Build and deploy ASP app to Azure Web App - intellitestapp01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "./Project 01 - Secure HR Portal/website-appservice/HRPortalApp.csproj"

      - name: Build
        run: dotnet build "./Project 01 - Secure HR Portal/website-appservice/HRPortalApp.csproj" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "./Project 01 - Secure HR Portal/website-appservice/HRPortalApp.csproj" --configuration Release --no-build --output "${{ github.workspace }}/published"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: "${{ github.workspace }}/published"

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC6F8EC061D44D78BB0844F40BE5CB61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9BD731053FF4650A15F319CA3277F2B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE4F861633BF473884900489154A322D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'intellitestapp01'
          slot-name: 'Production'
          package: ${{ github.workspace }}/ASP-app
